### ISSUE TITLE
pet hospital

### ISSUE THREAD

**Issue by q1joy** [a6678696/PetHospital#10]
能用一下这个项目的数据库么~自己不会建库表

**Comment by a6678696** [comment]
仓库里有数据库文件，你导入就行了

**Comment by q1joy** [comment]
谢谢！  连上了！但是还是没有可视化 ，显示SQL dialect is not configured，MariaDB  match best 这个咋弄得

**Comment by q1joy** [comment]
现在运行也不报错 也没反应不知道咋回事了

**Comment by q1joy** [comment]
前端的一些东西还没改 ，但功能也不显示，可视化出不来求助~

**Comment by a6678696** [comment]
根据你的提问我也不知道你出现什么问题，你遇到的问题和我的项目应该是没有关系的，数据库文件导入后就行了不会有什么问题
