### ISSUE TITLE
静态资源没有引进去  怎么处理

### ISSUE THREAD

**Issue by q1joy** [a6678696/PetHospital#12]

**Comment by q1joy** [comment]
静态资源如何引进

**Comment by a6678696** [comment]
前端静态资源的引入在`index.html`这个文件的`<head>`标签内，我使用的都是相对路径，应该不会有什么问题的，你清除一下浏览器的缓存试试看

![image](https://user-images.githubusercontent.com/45851356/194210261-b59c0d6b-2e45-4728-8f80-20ba2b0c8c07.png)

**Comment by q1joy** [comment]
大佬能帮我远协看一下么

**Comment by a6678696** [comment]
我现在没空，你先自己解决，实在不行的话，晚上9点~10点再来找我
