### ISSUE TITLE
静态资源问题

### ISSUE THREAD

**Issue by q1joy** [a6678696/PetHospital#13]
博主 ，我还是没有弄出来，网页跳转不了，图加载不出 ，麻烦您9点帮我看是哪里出了问题 ，万分感谢

**Comment by a6678696** [comment]
下载ToDesk，发设备代码和临时密码给我

**Comment by q1joy** [comment]
兄弟你太牛了，佩服佩服



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月6日(周四) 晚上10:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [a6678696/PetHospital] 静态资源问题 (Issue #13)




 
Closed #13 as completed.

**Comment by a6678696** [comment]
之所以出现这个问题，是因为你idea打开的不是真正的项目文件夹，第二个pethospital-master文件夹才是真的，下载好的代码在哪个文件夹就打开哪个文件夹

**Comment by q1joy** [comment]
懂了大哥，我项目文件夹包在里面了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月6日(周四) 晚上10:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [a6678696/PetHospital] 静态资源问题 (Issue #13)




 
之所以出现这个问题，是因为你idea打开的不是真正的项目文件夹，第二个pethospital-master文件夹才是真的，下载好的代码在哪个文件夹就打开哪个文件夹

**Comment by q1joy** [comment]
大哥，还有个问题，管理员的账号密码是什么啊，我找不到



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月6日(周四) 晚上10:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [a6678696/PetHospital] 静态资源问题 (Issue #13)




 
之所以出现这个问题，是因为你idea打开的不是真正的项目文件夹，第二个pethospital-master文件夹才是真的，下载好的代码在哪个文件夹就打开哪个文件夹

**Comment by q1joy** [comment]
救命我看表里有个 admin admin  试了发现进不去管理系统
