### ISSUE TITLE
发现bug两个

### ISSUE THREAD

**Issue by SevenLoveme** [a6678696/PetHospital#19]
![image](https://user-images.githubusercontent.com/69687544/196878790-3b9b2d91-d71a-4148-bfca-115e089e2486.png)
预约无法选择日期

![image](https://user-images.githubusercontent.com/69687544/196878860-5a583ffe-e393-40a6-99d6-b441b625dbbb.png)
我在后台看了是有医生的 但是在前台选择不了医生

**Comment by a6678696** [comment]
![image](https://user-images.githubusercontent.com/45851356/196951989-63cf1dc9-4ea7-4917-8581-075bd46266ae.png)
