### ISSUE TITLE
当我把定时任务设置为5秒钟后发生了这样的事

### ISSUE THREAD

**Issue by SevenLoveme** [a6678696/PetHospital#20]
![image](https://user-images.githubusercontent.com/69687544/198785460-38212c32-323b-4ed0-ba9f-d248df425ad0.png)
很多相同的时间 而且有很多条 请问这是怎么回事呢

**Comment by a6678696** [comment]
### 原因
你改成5秒钟并生成预约单后，却没停止项目的运行以及改回原来的cron表达式，导致每5秒钟就生成一次预约单。这些预约单本来是一天只生成一次的，而你却每5秒钟就生成一次。建议弄成20秒及以上的时间，不然可能会来不及操作
### 解决办法
你把预约表的数据都清空，然后按照我之前说的那样操作就没问题，请仔细看操作步骤，如下图所示（图中是两个解决办法而不是步骤）
![image](https://user-images.githubusercontent.com/45851356/198816160-f8290a27-76ae-4b02-8da5-236d7fe2d4d3.png)

**Comment by SevenLoveme** [comment]
懂了 谢谢解答




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "a6678696/PetHospital"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月29日(星期六) 中午1:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [a6678696/PetHospital] 当我把定时任务设置为5秒钟后发生了这样的事 (Issue #20)





 
原因
 
你改成5秒钟并生成预约单后，却没停止项目的运行以及改回原来的cron表达式，导致每5秒钟就生成一次预约单。这些预约单本来是一天只生成一次的，而你却每5秒钟就生成一次。建议弄成20秒及以上的时间，不然可能会来不及操作
 
解决办法
 
你把预约表的数据都清空，然后按照我之前说的那样操作就没问题，请仔细看操作步骤，如下图所示（图中是两个解决办法而不是步骤）

**Comment by SevenLoveme** [comment]
但是 定时任务中也应该添加删除才对 不然就算是每天生成 那么数据库中还是存在上一天的预约生成

**Comment by a6678696** [comment]
会自动删除过期的预约单

![image](https://user-images.githubusercontent.com/45851356/198817256-dce3ca0c-6eaf-4c3b-92ed-1f340976f59f.png)

**Comment by SevenLoveme** [comment]
好的
