### ISSUE TITLE
宠物寄养

### ISSUE THREAD

**Issue by zzfhmj** [a6678696/PetHospital#21]
请问宠物寄养只能后台添加吗？用户首页没有宠物寄养申请吗？后台日期请为什么不能选择

**Comment by a6678696** [comment]
只能后台添加宠物寄养记录，用户在前台没有宠物寄养申请，寄养日期是当前时间没有弄选择时间，你自己改代码实现你的需求吧

**Comment by zzfhmj** [comment]
好的，感谢
