### ISSUE TITLE
我从这儿克隆到idea怎么运行啊 怎么打开前台的页面 求博主教

### ISSUE THREAD

**Issue by rosewangzhen** [a6678696/PetHospital#7]

**Comment by a6678696** [comment]
要安装的环境有：JDK、Maven、MySQL，前台首页地址为：localhost，后台登录地址为：localhost/login.html

**Comment by rosewangzhen** [comment]
> 要安装的环境有：JDK、Maven、MySQL，前台首页地址为：localhost，后台登录地址为：localhost/login.html

环境都有  运行的时候数据库需要打开吗，有没有具体操作步骤呀博主

**Comment by rosewangzhen** [comment]
> 要安装的环境有：JDK、Maven、MySQL，前台首页地址为：localhost，后台登录地址为：localhost/login.html

我克隆到idea之后然后点击运行  他就一直在跑 没停下来  之后我应该怎么做呢   是直接打开浏览器输入地址吗

**Comment by a6678696** [comment]
你试试吧，如果不行就看看出什么问题，然后去百度解决
